### ISSUE TITLE
Windows 7 64-bit login interface has not changed

### ISSUE THREAD

**Issue by beautifulsonset** [charset/ScancodeCredentialProvider#1]
Hello, may I ask why I copied the 32-bit SampleAllControlsCredentialProvider.dll to the C:\Windows\SysWOW64 directory, registered the lock screen in the registry, there is no change in the login interface. Is it wrong with me?
Is there still some code missing from the TCP client?

**Comment by charset** [comment]
As my readme.txt in sampleallcontrolscredentialprovider folder says:
Copy the DLL to %WINDIR%\System32 and run the register.reg
whenever this dll built in 32-bit or 64-bit.
Windows might searches the credential providers only in System32 folder.

**Comment by beautifulsonset** [comment]
Thank you for your answer. After testing, there is no problem with the registry step, because I renamed the DLL generated by another example to SampleAllControlsCredentialProvider.dll and can be called normally. It should be that there is an exception in a function in this example, and the system does not call the DLL normally. I haven't found out what went wrong now.

The DLL generated by another example is renamed as the result of SampleAllControlsCredentialProvider.dll. The DLL generated by this code does not receive any debugging information, and the lock screen interface has not changed.
![image](https://user-images.githubusercontent.com/48896630/55382373-1176eb80-5558-11e9-94f1-c2cef3ecc55c.png)

**Comment by charset** [comment]
When I was debugging this project, if the credential provider did not shown up when booting, I just logged in system and loaded unregister.reg then register.reg again.
I guess if a credential provider gets fault and it would be marked as disabled.

Check your registry again: 

> https://social.technet.microsoft.com/Forums/windows/en-US/9c23976a-3e2b-4b71-9f19-83ee3df0848b/how-to-disable-additional-credential-providers

**Comment by charset** [comment]
Another reason why might be your DLL doesn’t match the class ID your registry registered.

**Comment by beautifulsonset** [comment]
I am sure that my DLL name matches the ID in the registry. I think it should be other credentials that affect my DLL.I feel very helpful in the link you gave, I am following the steps to try

**Comment by charset** [comment]
feel free @beautifulsonset
