### ISSUE TITLE
The lock screen will flash

### ISSUE THREAD

**Issue by beautifulsonset** [charset/ScancodeCredentialProvider#2]
Hello, author, the last time the DLL call was unsuccessful is the registry cache problem, just add the cleanup registry and add it. Now there are new problems. In win7 32-bit, after LogonUI.exe calls the compiled DLL after the lock screen, the screen will flash continuously. After a while, the following application error occurs. What went wrong? I just added the OutputDebugStringA() print message to the original code.
![image](https://user-images.githubusercontent.com/48896630/55800390-3c3be380-5b06-11e9-950c-8cea4ef3f5ab.png)
![image](https://user-images.githubusercontent.com/48896630/55800433-51b10d80-5b06-11e9-96b3-907fa9fefdd3.png)

**Comment by charset** [comment]
没有试过32位元的DLL，不过应该没问题吧。你是指这个微信二维码扫描的Credential Provider还是其他的？
理论上二维码扫的这个使用了一个我更新过的二维码生成组件，理论上需要把它编译成32位元的动态库。
调试Credential Provider非常痛苦，稍微一点错误都会导致闪屏，还是要遵循Windows规范来开发。

I didn't try 32-bit DLL. It should be OK without problem. Did you get your problem in this Scan Code Credential Provider or the others? I used a qrcode library which I modified and compiled into 64-bit DLL. If you compiled project into 32-bit you might need to compile qrcode library again in 32-bit too.
Debugging Credential Provider suffers. With tiny error it runs as splash screen. We should obey the windows developing rules.

**Comment by beautifulsonset** [comment]
Your new QR code is very good, I am already running, just have a black box
![image](https://user-images.githubusercontent.com/48896630/55844485-13e8cf00-5b70-11e9-914e-792d78298ee8.png)

**Comment by charset** [comment]
那应该是调用zint的问题
Should be zint lib invoking problems.

**Comment by beautifulsonset** [comment]
我使用的是zint2.4.2.dll,生成二维码没有问题，ZBarcode_Print(my_symbol, 0)可以再本地生成"QRCode.bmp"。调用SetDIBits(hCompatibleDC, hCompatibleBitmap, 0, my_symbol->bitmap_height, my_symbol->bitmap, &bmpi, DIB_RGB_COLORS)总是返回0，应该是这里的问题。
I am using zint2.4.2.dll, there is no problem generating QR code, ZBarcode_Print(my_symbol, 0) can generate "QRCode.bmp" locally. Calling SetDIBits(hCompatibleDC, hCompatibleBitmap, 0, my_symbol->bitmap_height, my_symbol->bitmap, &bmpi, DIB_RGB_COLORS) always returns 0, which should be the problem here.

**Comment by charset** [comment]
米有看到你代码 估计不太好定位 no code no location🌝

**Comment by charset** [comment]
看看getlasterror返回啥吧

**Comment by beautifulsonset** [comment]
![image](https://user-images.githubusercontent.com/48896630/55931583-b4b2b980-5c58-11e9-9436-ce92851ac0e3.png)
SetDIBits failed and return 0;

**Comment by charset** [comment]
我使用的24bit格式的bmp
会不会你那里用的是16bit格式的显示设置
懒得打英文了 见谅

**Comment by charset** [comment]
可以加一个getlasterror看看错误代码可以查到在setdbits的

**Comment by beautifulsonset** [comment]
![image](https://user-images.githubusercontent.com/48896630/55957933-1a736580-5c9a-11e9-8fcf-b96ffa1533fb.png)
![image](https://user-images.githubusercontent.com/48896630/55958051-5b6b7a00-5c9a-11e9-9d59-dbe0825a64ee.png)

SetDIBits（）后的LastError是5。

**Comment by beautifulsonset** [comment]
另外我想请教一下，VS2015 win32应用程序Demo使用LoadImage加载qrencode生成的二维码bmp图像总是无法显示，在你的代码里是用zint生成二维码的,但是调用ZBarcode_Print()只能生成png, loadImage不支持png显示图像。
以下是我写的Demo；麻烦你帮我分析一下，谢谢。

BOOL LoadBitmapFromBMPFile(LPTSTR szFileName, HBITMAP *phBitmap,
	HPALETTE *phPalette)
{

	BITMAP  bm;

	*phBitmap = NULL;
	*phPalette = NULL;

	// Use LoadImage() to get the image loaded into a DIBSection
	*phBitmap = (HBITMAP)LoadImage(NULL, szFileName, IMAGE_BITMAP, 0, 0,
		LR_CREATEDIBSECTION | LR_DEFAULTSIZE | LR_LOADFROMFILE);
	if (*phBitmap == NULL)
		return FALSE;

	// Get the color depth of the DIBSection
	GetObject(*phBitmap, sizeof(BITMAP), &bm);
	// If the DIBSection is 256 color or less, it has a color table
	if ((bm.bmBitsPixel * bm.bmPlanes) <= 8)
	{
		HDC           hMemDC;
		HBITMAP       hOldBitmap;
		RGBQUAD       rgb[256];
		LPLOGPALETTE  pLogPal;
		WORD          i;

		// Create a memory DC and select the DIBSection into it
		hMemDC = CreateCompatibleDC(NULL);
		hOldBitmap = (HBITMAP)SelectObject(hMemDC, *phBitmap);
		// Get the DIBSection's color table
		GetDIBColorTable(hMemDC, 0, 256, rgb);
		// Create a palette from the color tabl
		pLogPal = (LOGPALETTE *)malloc(sizeof(LOGPALETTE) + (256 * sizeof(PALETTEENTRY)));
		pLogPal->palVersion = 0x300;
		pLogPal->palNumEntries = 256;
		for (i = 0; i < 256; i++)
		{
			pLogPal->palPalEntry[i].peRed = rgb[i].rgbRed;
			pLogPal->palPalEntry[i].peGreen = rgb[i].rgbGreen;
			pLogPal->palPalEntry[i].peBlue = rgb[i].rgbBlue;
			pLogPal->palPalEntry[i].peFlags = 0;
		}
		*phPalette = CreatePalette(pLogPal);
		// Clean up
		free(pLogPal);
		SelectObject(hMemDC, hOldBitmap);
		DeleteDC(hMemDC);
	}
	else   // It has no color table, so use a halftone palette
	{
		HDC    hRefDC;

		hRefDC = GetDC(NULL);
		*phPalette = CreateHalftonePalette(hRefDC);
		ReleaseDC(NULL, hRefDC);
	}
	return TRUE;

}
以下是WndProc 部分代码
static HBITMAP bitmap = NULL; ;// 位图绘制对象句柄
	static LPTSTR szFileName = "test.bmp";
	switch(message)
	{
	case WM_CREATE:
		{
			
			
		}
		break;
	case WM_PAINT:
		{

		PAINTSTRUCT   ps;
		HBITMAP       hBitmap, hOldBitmap;
		HPALETTE      hPalette, hOldPalette;
		HDC           hDC, hMemDC;
		BITMAP        bm;

		hDC = BeginPaint(hWnd, &ps);

		if (LoadBitmapFromBMPFile(szFileName, &hBitmap, &hPalette))
		{
			GetObject(hBitmap, sizeof(BITMAP), &bm);
			hMemDC = CreateCompatibleDC(hDC);
			hOldBitmap = (HBITMAP)SelectObject(hMemDC, hBitmap);
			hOldPalette = SelectPalette(hDC, hPalette, FALSE);
			RealizePalette(hDC);

			BitBlt(hDC, 0, 0, bm.bmWidth, bm.bmHeight,
				hMemDC, 0, 0, SRCCOPY);

			SelectObject(hMemDC, hOldBitmap);
			DeleteObject(hBitmap);
			SelectPalette(hDC, hOldPalette, FALSE);
			DeleteObject(hPalette);
		}
		EndPaint(hWnd, &ps);
      }
break;
}

问题在于，如果 “test.bmp”是画图软件保存的bmp文件，loadimage就可以正常加载，如果是qrencode生成的bmp二维码图图片就不能加载，bmp图像我用Hex分析了headerinfo，是符合BMP无压缩的要求的。

**Comment by charset** [comment]
https://docs.microsoft.com/en-us/windows/desktop/Debug/system-error-codes--0-499-
ERROR_ACCESS_DENIED
5 (0x5)
Access is denied.
很奇怪的错误呢。
后一个问题中，为什么需要使用调色板呢？
我记得如果是32位元或者16位元的色彩，是不需要调色板的，调色板应该在256色以下的环境中才需要用到。如果不是的话，似乎创建了一个 halftone palette。
https://support.microsoft.com/en-us/help/158898/howto-how-to-use-loadimage-to-read-a-bmp-file
代码似乎是从这里的，等会儿可以测试一下。
另外似乎你在8小时之外回复的，在一个工作不能上外网的工作单位？

**Comment by charset** [comment]
不介意的话+wx://11199317讨论？

**Comment by beautifulsonset** [comment]
我对win32的理解不是很深，前面的bmp图片不显示问题是qrencode生成二维码的时候设置的bitlength设置成了负数，但是在Windows上API只识别正的长度，所以才会导致loadImage不成功；你的例子源码编译后也不显示二维码有可能与此有关系，不同的是你生成二维码是用zint生成的。
